-- Run in Supabase SQL Editor. This app uses its own JWT/bcrypt authentication, not Supabase Auth.
create extension if not exists "pgcrypto";
create table if not exists users (id uuid primary key default gen_random_uuid(), name text not null, email text not null unique, password text not null, role text not null default 'customer' check(role in ('customer','admin')), avatar_url text, is_active boolean not null default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists addresses (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade not null, full_name text not null, phone text not null, line1 text not null, line2 text, city text not null, state text not null, postal_code text not null, country text not null default 'India', is_default boolean default false, created_at timestamptz default now());
create table if not exists categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, description text, image_url text, created_at timestamptz default now());
create table if not exists products (id uuid primary key default gen_random_uuid(), category_id uuid references categories(id) on delete set null, name text not null, slug text not null unique, brand text, description text, specifications jsonb default '{}', price numeric(12,2) not null check(price>=0), original_price numeric(12,2), stock integer not null default 0 check(stock>=0), average_rating numeric(3,2) default 0, review_count integer default 0, is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists product_images (id uuid primary key default gen_random_uuid(), product_id uuid references products(id) on delete cascade not null, url text not null, alt_text text, position integer default 0);
create table if not exists product_variants (id uuid primary key default gen_random_uuid(), product_id uuid references products(id) on delete cascade not null, sku text unique, color text, size text, price numeric(12,2), stock integer default 0, attributes jsonb default '{}');
create table if not exists cart (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade unique not null, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists cart_items (id uuid primary key default gen_random_uuid(), cart_id uuid references cart(id) on delete cascade not null, product_id uuid references products(id) on delete cascade not null, variant_id uuid references product_variants(id) on delete set null, quantity integer not null check(quantity>0), unique(cart_id,product_id,variant_id));
create table if not exists wishlist_items (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade not null, product_id uuid references products(id) on delete cascade not null, created_at timestamptz default now(), unique(user_id,product_id));
create table if not exists coupons (id uuid primary key default gen_random_uuid(), code text not null unique, type text not null check(type in ('percentage','fixed')), value numeric(12,2) not null, min_order_amount numeric(12,2) default 0, expires_at timestamptz, usage_limit integer, used_count integer default 0, is_active boolean default true, created_at timestamptz default now());
create table if not exists orders (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) not null, address_id uuid references addresses(id), coupon_id uuid references coupons(id), status text not null default 'Ordered' check(status in ('Ordered','Confirmed','Shipped','Out for Delivery','Delivered','Cancelled','Return Requested','Refunded')), subtotal numeric(12,2) not null, discount numeric(12,2) default 0, shipping numeric(12,2) default 0, total numeric(12,2) not null, payment_method text not null default 'test', payment_status text default 'pending', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists order_items (id uuid primary key default gen_random_uuid(), order_id uuid references orders(id) on delete cascade not null, product_id uuid references products(id), variant_id uuid references product_variants(id), product_name text not null, unit_price numeric(12,2) not null, quantity integer not null, created_at timestamptz default now());
create table if not exists reviews (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade not null, product_id uuid references products(id) on delete cascade not null, rating integer not null check(rating between 1 and 5), comment text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(user_id,product_id));
create table if not exists notifications (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade not null, type text not null, title text not null, body text not null, is_read boolean default false, metadata jsonb default '{}', created_at timestamptz default now());
create table if not exists price_history (id uuid primary key default gen_random_uuid(), product_id uuid references products(id) on delete cascade not null, old_price numeric(12,2) not null, new_price numeric(12,2) not null, changed_at timestamptz default now());
create table if not exists recently_viewed (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade not null, product_id uuid references products(id) on delete cascade not null, viewed_at timestamptz default now(), unique(user_id,product_id));
create table if not exists recommendations (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade not null, product_id uuid references products(id) on delete cascade not null, reason text not null, score numeric default 0, created_at timestamptz default now(), unique(user_id,product_id));
create index if not exists idx_products_category on products(category_id); create index if not exists idx_products_price on products(price); create index if not exists idx_orders_user on orders(user_id); create index if not exists idx_notifications_user on notifications(user_id); create index if not exists idx_reviews_product on reviews(product_id);
-- Enable RLS as a defense-in-depth default; the backend service role deliberately bypasses it.
alter table users enable row level security; alter table products enable row level security;
